### ISSUE TITLE
Invalid deserialization of numbers

### ISSUE THREAD

**Issue by petabyteboy** [Diggsey/ijson#2]
The json string says:

```
"x":13369629,"y":52524924
```

Once parsed into an IValue, it says:

```
x: -3407587, y: 52524924
```

This does not happen when I use a `serde_json::Value`.

**Comment by Diggsey** [comment]
Hi @petabyteboy, thanks for the report.

This issue was caused by incorrect bounds checking during the intermediate-size integer storage optimization. (It checked if the value would fit in an unsigned 24-bit integer, when it should have checked if it would fit in a signed 24-bit integer).

I've updated the test suite to cover this case and published a new version of the crate (0.1.1) with the fix. I've yanked the previous versions of the crate.

Please let me know if you find any more issues!
